global:
  scrape_interval:     5s # By default, scrape targets every 15 seconds.
  evaluation_interval: 5s # By default, scrape targets every 15 seconds.

scrape_configs:
  - job_name: cadvisor
    scrape_interval: 5s
    metrics_path: /q/metrics
    static_configs:
      - targets:
          - randoli_web_1:8080

